library(VennDetail)
context("venndetail")
A <- sample(1:100, 40, replace = FALSE)
B <- sample(1:100, 60, replace = FALSE)
C <- sample(1:100, 40, replace = FALSE)
expect_silent(res<-venndetail(list(A = A,B = B,C = C)))
